---
apiVersion:  v1
kind: Service
metadata:
  name: tor-service
spec:
  # type: ClusterIP
  selector:
    app: tor-relay
  ports:
  - name: tor
    protocol: TCP
    port: 9010
  - name: tor-dir
    protocol: TCP
    port: 9031
  externalIPs:
    - 192.168.1.151
