---
kind: Kustomization

namespace: nfs-provisioner
resources:
  - namespace.yml
  - secrets.yml

helmChartInflationGenerator:
- chartName: democratic-csi
  chartRepoUrl: https://democratic-csi.github.io/charts/
  chartVersion: 0.13.5
  releaseName: nfs-provisioner
  releaseNamespace: nfs-provisioner
  values: values.yml
