---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: nfs-cred
  namespace: nfs-provisioner
spec:
  path: k8s-prrlvr/nfs-provisioner/credentials
  keys:
    - http-password
    - http-user
    - ssh-user
    - ssh-password
  type: Opaque
---
