---
kind: ConfigMap
apiVersion: v1
metadata:
  name: init-jackett-cm
data:
  ServerConfig.json: |
    {
      "BasePathOverride": "/jackett"
    }
  init-jackett.sh: |
    #!/bin/bash
    echo "### Initializing config ###"
    if [ -f /init-jackett/ServerConfig.json ]; then
      cp -n /init-jackett/ServerConfig.json /jackett-config/ServerConfig.json
    fi
