---
kind: ConfigMap
apiVersion: v1
metadata:
  name: init-sonarr-cm
data:
  config.xml: |
    <Config>
    <UrlBase>/sonarr</UrlBase>
    </Config>
  init-sonarr.sh: |
    #!/bin/bash
    echo "### Initializing config ###"
    if [ -f /init-sonarr/config.xml ]; then
      cp -n /init-sonarr/config.xml /sonarr-config/config.xml
    fi
