---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-datadir
  annotations:
    nfs.io/storage-path: "minio"
  labels:
    app: minio
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
