all:
  hosts:
    node1:
      ansible_host: 192.168.1.110
      ansible_port: 22
      ansible_user: ubuntu
      ansible_become: true
      ip: 192.168.1.110
      access_ip: 192.168.1.110
    node2:
      ansible_host: 192.168.1.120
      ansible_port: 22
      ansible_user: ubuntu
      ansible_become: true
      ip: 192.168.1.120
      access_ip: 192.168.1.120
    node3:
      ansible_host: 192.168.1.121
      ansible_port: 22
      ansible_user: ubuntu
      ansible_become: true
      ip: 192.168.1.121
      access_ip: 192.168.1.121
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
