all:
  hosts:
    node1:
      ansible_host: 192.168.1.201
      ansible_user: root
      ip: 192.168.1.201
      access_ip: 192.168.1.201
      local_as: 64512
    node2:
      ansible_host: 192.168.1.202
      ansible_user: root
      ip: 192.168.1.202
      access_ip: 192.168.1.202
      local_as: 64512
    node3:
      ansible_host: 192.168.1.203
      ansible_user: root
      ip: 192.168.1.203
      access_ip: 192.168.1.203
      local_as: 64512
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
