---
kind: Kustomization
namespace: vaultwarden

resources:
  - namespace.yml
  - pvc.yml
  - secrets.yml
  - deployment.yml
  - service.yml
  - ingress.yml

configMapGenerator:
  - name: vaultwarden-configmap
    literals:
      - ROCKET_PORT=8080
      - SIGNUPS_ALLOWED=true
      - SHOW_PASSWORD_HINT=false
      - WEBSOCKET_ENABLED=true
      - WEB_VAULT_ENABLED=true
      - DOMAIN=https://vaultwarden.prrlvr.fr
      - DISABLE_ADMIN_TOKEN=false

images:
  - name: vaultwarden/server
    newTag: 1.25.2
