---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: prrlvr-main-cluster
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
spec:
  teamId: prrlvr
  volume:
    storageClass: nfs-client
    size: 10Gi
  numberOfInstances: 1

  # users: name -> permissions (usually [])
  users:
    gitea: []

  # databases: name -> owner
  databases:
    gitea: gitea

  postgresql:
    version: "14"
    parameters:
      max_connections: "500"
      wal_keep_segments: "128"
  sidecars:
    - name: "exporter"
      image: quay.io/prometheuscommunity/postgres-exporter:v0.11.1
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 256M
        requests:
          cpu: 100m
          memory: 200M
      env:
        - name: DATA_SOURCE_URI
          value: "prrlvr-main-cluster?sslmode=require"
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: postgres.prrlvr-main-cluster.credentials
              key: username
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres.prrlvr-main-cluster.credentials
              key: password
        - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
          value: "true"
