---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: prrlvr-main-cluster

spec:
  teamId: prrlvr
  volume:
    storageClass: nfs-client
    size: 10Gi
  numberOfInstances: 2

  # users: name -> permissions (usually [])
  users:
    gitea.gitea: []
    nextcloud.nextcloud: []
    keycloak.keycloak: []
    vaultwarden.vaultwarden: []

  # databases: name -> owner
  databases:
    gitea: gitea.gitea
    nextcloud: nextcloud.nextcloud
    keycloak: keycloak.keycloak
    vaultwarden: vaultwarden.vaultwarden

  patroni:
    pg_hba:
      - local     all           all                                   trust
      - host      all           all                127.0.0.1/32       md5
      - host      all           all                ::1/128            md5
      - local     replication   standby                               trust
      - hostssl   replication   standby all                           md5
      - hostnossl all           all                all                md5
      - hostssl   all           all                all                md5

  postgresql:
    version: "14"
    parameters:
      max_connections: "500"
      wal_keep_segments: "128"
