---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: oidc-keycloak
spec:
  path: k8s-prrlvr/argocd/oidc-keycloak
  keys:
    - oidc.keycloak.clientId
    - oidc.keycloak.clientSecret
  type: Opaque
