---
apiVersion: v1
kind: Secret
metadata:
  name: gitea.prrlvr-main-cluster.credentials
  namespace: gitea
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/gitea.prrlvr-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: gitea-admin
  namespace: gitea
spec:
  path: k8s-prrlvr/gitea/admin
  keys:
    - username
    - password
    - email
  type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  project: default
  source:
    repoURL: https://dl.gitea.io/charts/
    chart: gitea
    targetRevision: 6.0.0
    helm:
      values: |
        fullnameOverride: gitea
        global:
          replicaCount: 1
        image:
          tag: 1.17
          pullPolicy: Always
          rootless: false
        gitea:
          admin:
            existingSecret: gitea-admin
          metrics:
            enabled: false
          config:
            database:
              DB_TYPE: postgres
              HOST: prrlvr-main-cluster.postgres.svc.k8s.prrlvr.local
              NAME: gitea
              USER: gitea
              SCHEMA: public
              SSL_MODE: require
            cache:
              ENABLED: false
            server:
              ROOT_URL: https://%(DOMAIN)s/
          additionalConfigFromEnvs:
            - name: ENV_TO_INI__DATABASE__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea.prrlvr-main-cluster.credentials
                  key: password
        postgresql:
          enabled: false
        memcached:
          enabled: false
        signing:
          enabled: true
        persistence:
          enabled: true
          storageClass: nfs-client
          size: 20Gi
        image:
          rootless: false
        service:
          ssh:
            type: ClusterIP
            port: 22
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: gitea.k8s.prrlvr.fr
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - gitea.k8s.prrlvr.fr
              secretName: gitea-tls
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
