---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.1.4
    helm:
      values: |
        controller:
          hostNetwork: true
          kind: "DaemonSet"
          watchIngressWithoutClass: true
          dnsPolicy: "ClusterFirstWithHostNet"
          service:
            type: ""
          metrics:
            enabled: true
            serviceMonitor:
              enabled: false
          publishService:
            enabled: false
          extraArgs:
            publish-status-address: 82.65.187.116
        defaultBackend:
          enabled: true
          replicaCount: 1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
