---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.1.4
    helm:
      values: |
        controller:
          hostNetwork: true
          kind: "DaemonSet"
          watchIngressWithoutClass: true
          dnsPolicy: "ClusterFirstWithHostNet"
          service:
            type: ""
          metrics:
            enabled: true
            serviceMonitor:
              enabled: false
          publishService:
            enabled: false
          extraArgs:
            publish-status-address: 77.207.207.191
        defaultBackend:
          enabled: true
          replicaCount: 1
        tcp:
          22: gitea/gitea-ssh:22
          9010: tor-relay/tor-service:9010
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
