---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/prrlvr/infrastructure.git
    targetRevision: HEAD
    path: k8s/postgres
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: false
