---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/prrlvr/infrastructure.git
    targetRevision: HEAD
    path: k8s/renovate
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
