---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator
  project: default
  source:
    repoURL: https://ricoberger.github.io/helm-charts
    chart: vault-secrets-operator
    targetRevision: 1.19.2
    helm:
      values: |
        fullnameOverride: vault-secrets-operator
        vault:
          authMethod: approle
          address: https://vault.k8s.prrlvr.fr
        serviceMonitor:
          enabled: false
        environmentVars:
          - name: VAULT_ROLE_ID
            valueFrom:
              secretKeyRef:
                name: vault-approle
                key: VAULT_ROLE_ID
          - name: VAULT_SECRET_ID
            valueFrom:
              secretKeyRef:
                name: vault-approle
                key: VAULT_SECRET_ID
          - name: VAULT_TOKEN_MAX_TTL
            valueFrom:
              secretKeyRef:
                name: vault-approle
                key: VAULT_TOKEN_MAX_TTL
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
