---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii
  labels:
    app: firefly-iii
spec:
  selector:
    matchLabels:
      app: firefly-iii
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: firefly-iii
        tier: frontend
    spec:
      containers:
      - name: firefly-iii
        image: fireflyiii/core:version-5.7.18
        imagePullPolicy: Always
        env:
        - name: APP_ENV
          value: "local"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: firefly-core
              key: app_key
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_HOST
          value: prrlvr-main-cluster.postgres.svc.k8s.prrlvr.local
        - name: DB_PORT
          value: 5432
        - name: DB_DATABASE
          value: "firefly"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
                  name: firefly.firefly.prrlvr-main-cluster.credentials
                  key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
                  name: firefly.firefly.prrlvr-main-cluster.credentials
                  key: password
        - name: TRUSTED_PROXIES
          value: "**"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: "/var/www/html/storage/upload"
          name: upload-datadir
      volumes:
        - name: upload-datadir
          persistentVolumeClaim:
            claimName: firefly-iii-upload-datadir
