---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-upload-datadir
  labels:
    app: firefly-iii
spec:
  storageClass: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
